#! /bin/sh -f
export RASPA_DIR=/home/ambroise/Desktop/Construction_default/RASPA_default_zeolithes/simulations/
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
$RASPA_DIR/bin/simulate $1
